sudo: required
dist: bionic
language: cpp
compiler:
    - g++
    - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install pkg-config -y
  - sudo apt-get install libfftw3-dev -y
  - sudo apt-get install libgraphicsmagick++1-dev -y
  - sudo apt-get install libluajit-5.1-dev -y
  - sudo apt-get install qt5-default -y
  - if [[ $CXX == "clang++" ]]; then export QMSPEC="-spec linux-clang"; fi

install:
  - qmake $QMSPEC lines.pro

script:
  - make
